# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MWvIfgxZVRuc2C1PyQGJfC-qCxzIJtGQ
"""

import pandas as pd
import random
lst = ['robot'] * 10
lst += ['human'] * 10
random.shuffle(lst)
data = pd.DataFrame({'whoAmI':lst})
data.head()

for i in range(len(lst)):
    if lst[i] == 'human':
        lst[i] = 1
    else:
        lst[i] = 0

data = pd.DataFrame({'human':lst})
data.head()

data.loc[data['human'] == 1, 'robot'] = 0
data.loc[data['human'] == 0, 'robot'] = 1
data['robot'] = data['robot'].astype(int)
data.head(20)

































